* added platform flag

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -35,6 +35,7 @@ fi
 #
 # Defaults
 #
+platform=''
 cc='gcc'
 ccver='auto'
 depflags=''
@@ -147,6 +148,22 @@ EOF
   ;;
   esac
 done
+
+#
+# Get build platform (either linux or freebsd)
+#
+platform=`uname`
+legal=
+for legal_platform in Linux FreeBSD ; do
+    if [ $platform = $legal_platform ] ; then
+	legal=1
+    fi
+done
+if [ -z "$legal" ] ; then
+    echo "error: building oasys on unsupported platform $platform"
+    exit 1
+fi
+platform="-D__${platform}__"
 
 #
 # Make sure the compiler a) works b) is some gcc variant and c) is an
@@ -311,6 +328,7 @@ done
 #
 # Spit out some output and then do the correct substitution on Rules.make
 #
+echo "Platform:  $platform"
 echo "Target/Tools:"
 echo "  SRCDIR: $srcdir"
 echo "  CC: $cc"
@@ -343,6 +361,7 @@ s%@INCDIRS@%$incdirs%g
 s%@LIBDIRS@%$libdirs%g
 s%@LIBS@%$libs%g
 s%@STATIC_LIBS@%$staticlibs%g
+s%@PLATFORM@%$platform%g
 
 " $srcdir/Rules.make.in >> Rules.make
 
