add a configure check and a shell script to fix the problem for a conflicting debug.h in the c++ compiler installation on OS X.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2854,6 +2854,94 @@ echo "$as_me: error: broken std::string::reserve() -- upgrade your compiler" >&2
 
 
 
+
+   echo "$as_me:$LINENO: checking whether a conflicting debug/debug.h exists (Apple OSX only)" >&5
+echo $ECHO_N "checking whether a conflicting debug/debug.h exists (Apple OSX only)... $ECHO_C" >&6
+   if test `uname` = 'Darwin' ; then
+   ac_ext=cc
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+       cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <debug/Debug.h>
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+
+           echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+	   echo "***"
+	   echo "*** The C++ compiler installation on this host contains a file"
+	   echo "*** debug/debug.h which, when included by the preprocessor,"
+	   echo "*** conflicts with debug/Debug.h from the oasys source."
+	   echo "***"
+	   echo "*** To fix the problem, this configure script can rename the"
+	   echo "*** file debug.h to apple-debug.h, and will change all"
+	   echo "*** #include references using the script fix-apple-debug-header.sh."
+	   echo "***"
+	   echo $ECHO_N "*** Should this script run 'sudo sh fix-apple-debug-header.sh'... [no] $ECHO_C"
+	   read response
+	   if test x$response = x'yes' -o x$response = x'y' ; then
+	       echo "*** Running sudo sh fix-apple-debug-header.sh..."
+	       sudo sh fix-apple-debug-header.sh
+	       if test ! $? = 0 ; then
+	           { { echo "$as_me:$LINENO: error: running fix-apple-debug-header.sh. must reconcile manually" >&5
+echo "$as_me: error: running fix-apple-debug-header.sh. must reconcile manually" >&2;}
+   { (exit 1); exit 1; }; }
+	       fi
+           else
+	       { { echo "$as_me:$LINENO: error: conflict in debug/debug.h exists. must reconcile manually" >&5
+echo "$as_me: error: conflict in debug/debug.h exists. must reconcile manually" >&2;}
+   { (exit 1); exit 1; }; }
+           fi
+
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+	   echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+       ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+   else
+      echo "$as_me:$LINENO: result: no check needed" >&5
+echo "${ECHO_T}no check needed" >&6
+   fi
+
 echo "$as_me:$LINENO: checking for library containing pthread_create" >&5
 echo $ECHO_N "checking for library containing pthread_create... $ECHO_C" >&6
 if test "${ac_cv_search_pthread_create+set}" = set; then
