fix check for fpclassify to be a bit more robust

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5389,20 +5389,70 @@ fi
 done
 
 
+
 # This is most likely not the best "autoconfy" way of doing this...
 echo "$as_me:$LINENO: checking whether math.h defines fpclassify" >&5
 echo $ECHO_N "checking whether math.h defines fpclassify... $ECHO_C" >&6
-grep fpclassify /usr/include/math.h > /dev/null 2> /dev/null
-if test $? = 0 ; then
+
+if test "${dtn_cv_func_fpclassify+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+  dtn_cv_func_fpclassify=0
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+    #define _GNU_SOURCE 1
+    #include <math.h>
+    #ifndef fpclassify
+    #error no fpclassify
+    #endif
+
+int
+main ()
+{
+int main() {}
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  dtn_cv_func_fpclassify=1
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+
+
+if test $dtn_cv_func_fpclassify = 1 ; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_FPCLASSIFY
 _ACEOF
 
-    echo "$as_me:$LINENO: result: yes" >&5
+  echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 else
-    echo "$as_me:$LINENO: result: no" >&5
+  echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
